### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by wertyuilife** [nicklashansen/tdmpc2#20] opened 2024-03-06 11:35 UTC
I encountered a weird bug while attempting to train tdmpc on a single task. Specifically, the bug only manifests when setting the `steps` argument to 500,000; it does not occur otherwise.

Command:

```
python train.py task=walker-walk steps=500000
```

Error Message:

```
...
 train            E: 996                   I: 498,500               R: 954.8                 S: 0.0                   T: 10:36:54           
 train            E: 997                   I: 499,000               R: 961.6                 S: 0.0                   T: 10:37:23           
 train            E: 998                   I: 499,500               R: 995.2                 S: 0.0                   T: 10:37:51           
Error executing job with overrides: ['task=walker-walk', 'steps=500000', 'exp_name=test_tdmpc2_full', 'seed=1']
Traceback (most recent call last):
  File "/home/wangyuhang/Codes/tdmpc2/tdmpc2/train.py", line 57, in train
    trainer.train()
  File "/home/wangyuhang/Codes/tdmpc2/tdmpc2/trainer/online_trainer.py", line 112, in train
    _train_metrics = self.agent.update(self.buffer)
  File "/home/wangyuhang/Codes/tdmpc2/tdmpc2/tdmpc2.py", line 228, in update
    obs, action, reward, task = buffer.sample()
  File "/home/wangyuhang/Codes/tdmpc2/tdmpc2/common/buffer.py", line 94, in sample
    td = self._buffer.sample().view(-1, self.cfg.horizon+1).permute(1, 0)
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/site-packages/torchrl/data/replay_buffers/replay_buffers.py", line 450, in sample
    ret = self._prefetch_queue.popleft().result()
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/site-packages/torchrl/data/replay_buffers/utils.py", line 47, in decorated_fun
    output = fun(self, *args, **kwargs)
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/site-packages/torchrl/data/replay_buffers/replay_buffers.py", line 379, in _sample
    index, info = self._sampler.sample(self._storage, batch_size)
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/site-packages/torchrl/data/replay_buffers/samplers.py", line 769, in sample
    return self._sample_slices(lengths, start_idx, stop_idx, seq_length, num_slices)
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/site-packages/torchrl/data/replay_buffers/samplers.py", line 783, in _sample_slices
    raise RuntimeError(
RuntimeError: Some stored trajectories have a length shorter than the slice that was asked for. Create the sampler with `strict_length=False` to allow shorter trajectories to appear in you batch.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

Environment:
System: Ubuntu18.04
GPU: NVIDIA GeForce RTX 3090
Python Environment (conda) and Code: Follow the commit 57158282b46ebc5c329c5be9cfe2b0094126d1ca.

Additional Notes:

1. The error specifically occurs at the final training step; the training process proceeds as expected up to step 499,500, as per the log.
2. Modifying compute cost does not affect the code's behavior. For quicker reproduction, you may set `model_size=1 iterations=1 horizon=2`.
3. Several other commands with different `steps` arguments were attempted, and the code executed without error if `steps` is not equal to 500k:

```
(works fine)
python train.py task=walker-walk steps=10000 model_size=1 iterations=1 horizon=2
python train.py task=walker-walk steps=100000 model_size=1 iterations=1 horizon=2
python train.py task=walker-walk steps=200000 model_size=1 iterations=1 horizon=2
python train.py task=walker-walk steps=499000 model_size=1 iterations=1 horizon=2
python train.py task=walker-walk steps=501000 model_size=1 iterations=1 horizon=2
python train.py task=walker-walk steps=600000 model_size=1 iterations=1 horizon=2
python train.py task=walker-walk steps=700000 model_size=1 iterations=1 horizon=2
python train.py task=walker-walk steps=1000000 model_size=1 iterations=1 horizon=2

(error occurs)
python train.py task=walker-walk steps=500000 
python train.py task=walker-walk steps=500000 model_size=1 iterations=1 horizon=2
python train.py task=walker-walk steps=500000 seed=3 model_size=1 iterations=1 horizon=2
python train.py task=walker-walk steps=500000 seed=5 model_size=1 iterations=1 horizon=2
```

It appears that the episode lengths are not consistent as expected. However, it remains unclear why this inconsistency arises only when steps=500k.

For more environment details, this is the `conda list` result:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
absl-py                   2.0.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
aom                       3.4.0                h27087fc_1    conda-forge
appdirs                   1.4.4                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
blas                      1.0                         mkl    defaults
blessed                   1.20.0                   pypi_0    pypi
blinker                   1.7.0                    pypi_0    pypi
brotli-python             1.1.0            py39h3d6467e_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
comm                      0.2.1                    pypi_0    pypi
configargparse            1.7                      pypi_0    pypi
contourpy                 1.2.0                    pypi_0    pypi
cuda-cudart               12.1.105                      0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-libraries            12.1.0                        0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-opencl               12.3.101                      0    nvidia
cuda-runtime              12.1.0                        0    nvidia
cudatoolkit               11.7.0              hd8887f6_10    nvidia
cycler                    0.12.1                   pypi_0    pypi
cython                    0.29.37                  pypi_0    pypi
dash                      2.15.0                   pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
dm-control                1.0.8                    pypi_0    pypi
dm-env                    1.6                      pypi_0    pypi
dm-tree                   0.1.8                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
expat                     2.5.0                hcb278e6_1    conda-forge
fasteners                 0.19                     pypi_0    pypi
fastjsonschema            2.19.1                   pypi_0    pypi
ffmpeg                    1.4                      pypi_0    pypi
filelock                  3.13.1             pyhd8ed1ab_0    conda-forge
flask                     3.0.2                    pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.49.0                   pypi_0    pypi
freetype                  2.12.1               h267a509_2    conda-forge
fsspec                    2024.2.0                 pypi_0    pypi
gettext                   0.21.1               h27087fc_0    conda-forge
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.42                   pypi_0    pypi
glew                      2.1.0                h9c3ff4c_2    conda-forge
glfw                      2.6.4                    pypi_0    pypi
glib                      2.68.4               h9c3ff4c_0    conda-forge
glib-tools                2.68.4               h9c3ff4c_0    conda-forge
gmp                       6.3.0                h59595ed_0    conda-forge
gmpy2                     2.1.2            py39h376b7d2_1    conda-forge
gnutls                    3.7.6                hbf5b4be_4    conda-forge
gpustat                   1.1.1                    pypi_0    pypi
grpcio                    1.62.0                   pypi_0    pypi
gym                       0.21.0                   pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
hydra-submitit-launcher   1.2.0                    pypi_0    pypi
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
imageio                   2.33.1                   pypi_0    pypi
imageio-ffmpeg            0.4.9                    pypi_0    pypi
importlib-metadata        7.0.1                    pypi_0    pypi
importlib-resources       6.1.1                    pypi_0    pypi
ipython                   8.18.1                   pypi_0    pypi
ipywidgets                8.1.2                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.3              pyhd8ed1ab_0    conda-forge
joblib                    1.3.2                    pypi_0    pypi
jpeg                      9e                   h166bdaf_2    conda-forge
jsonschema                4.21.1                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter-core              5.7.1                    pypi_0    pypi
jupyterlab-widgets        3.0.10                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
kornia                    0.7.1                    pypi_0    pypi
labmaze                   1.0.6                    pypi_0    pypi
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.15                 hfd0df8a_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libcublas                 12.1.0.26                     0    nvidia
libcufft                  11.0.2.4                      0    nvidia
libcufile                 1.8.1.2                       0    nvidia
libcurand                 10.3.4.107                    0    nvidia
libcusolver               11.4.4.55                     0    nvidia
libcusparse               12.0.2.55                     0    nvidia
libdeflate                1.17                 h0b41bf4_0    conda-forge
libdrm                    2.4.120              hd590300_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libglib                   2.68.4               h3e27bee_0    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libhwloc                  2.9.3           default_h554bfaf_1009    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libidn2                   2.3.7                hd590300_0    conda-forge
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch-nightly
libnpp                    12.0.2.50                     0    nvidia
libnvjitlink              12.1.105                      0    nvidia
libnvjpeg                 12.1.1.14                     0    nvidia
libpciaccess              0.18                 hd590300_0    conda-forge
libpng                    1.6.42               h2797004_0    conda-forge
libsqlite                 3.45.1               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libtasn1                  4.19.0               h166bdaf_0    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libva                     2.18.0               h0b41bf4_0    conda-forge
libvpx                    1.11.0               h9c3ff4c_3    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.12.5               h232c23b_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-openmp               15.0.7               h0cdce71_0    conda-forge
lxml                      5.1.0                    pypi_0    pypi
markdown                  3.5.2                    pypi_0    pypi
markupsafe                2.1.5            py39hd1e30aa_0    conda-forge
matplotlib                3.8.3                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mkl                       2021.4.0           h8d4b97c_729    conda-forge
mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
mkl_random                1.2.2            py39hde0f152_0    conda-forge
moviepy                   1.0.3                    pypi_0    pypi
mpc                       1.3.1                hfe3b2da_0    conda-forge
mpfr                      4.2.1                h9458935_0    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
mujoco                    2.3.1                    pypi_0    pypi
mujoco-py                 2.1.2.14                 pypi_0    pypi
nbformat                  5.9.2                    pypi_0    pypi
ncurses                   6.4                  h59595ed_2    conda-forge
nest-asyncio              1.6.0                    pypi_0    pypi
nettle                    3.8.1                hc379101_1    conda-forge
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
numpy                     1.23.5                   pypi_0    pypi
nvidia-ml-py              12.535.133               pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
open3d                    0.18.0                   pypi_0    pypi
opencv-contrib-python     4.9.0.80                 pypi_0    pypi
opencv-python             4.9.0.80                 pypi_0    pypi
openh264                  2.3.0                h27087fc_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   1.1.1w               hd590300_0    conda-forge
p11-kit                   0.23.21              hb875675_1    conda-forge
packaging                 23.2                     pypi_0    pypi
pandas                    2.1.4                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
patchelf                  0.17.2.1                 pypi_0    pypi
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.9.0                    pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
platformdirs              4.2.0                    pypi_0    pypi
plotly                    5.19.0                   pypi_0    pypi
proglog                   0.1.10                   pypi_0    pypi
prompt-toolkit            3.0.43                   pypi_0    pypi
protobuf                  4.25.2                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pyopengl                  3.1.7                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.0           hffdb5ce_5_cpython    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytorch                   2.3.0.dev20240224 py3.9_cuda12.1_cudnn8.9.2_0    pytorch-nightly
pytorch-cuda              12.1                 ha16c6d3_5    pytorch-nightly
pytorch-mutex             1.0                        cuda    pytorch-nightly
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1            py39hd1e30aa_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
referencing               0.33.0                   pypi_0    pypi
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
retrying                  1.3.4                    pypi_0    pypi
rpds-py                   0.18.0                   pypi_0    pypi
sapien                    2.2.1                    pypi_0    pypi
scikit-learn              1.4.1.post1              pypi_0    pypi
scipy                     1.12.0                   pypi_0    pypi
sentry-sdk                1.40.5                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                65.5.0                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     5.0.1                    pypi_0    pypi
sqlite                    3.45.1               h2c6b66d_0    conda-forge
stack-data                0.6.3                    pypi_0    pypi
submitit                  1.5.1                    pypi_0    pypi
svt-av1                   1.2.0                h27087fc_0    conda-forge
sympy                     1.12            pypyh9d50eac_103    conda-forge
tbb                       2021.11.0            h00ab1b0_1    conda-forge
tenacity                  8.2.3                    pypi_0    pypi
tensorboard               2.16.2                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensordict-nightly        2024.1.10                pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
threadpoolctl             3.3.0                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
torchrl-nightly           2024.1.10                pypi_0    pypi
torchtriton               3.0.0+901819d2b6            py39    pytorch-nightly
torchvision               0.18.0.dev20240224      py39_cu121    pytorch-nightly
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.14.1                   pypi_0    pypi
transforms3d              0.4.1                    pypi_0    pypi
trimesh                   4.0.9                    pypi_0    pypi
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
wandb                     0.16.2                   pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.38.0                   pypi_0    pypi
widgetsnbextension        4.0.10                   pypi_0    pypi
x264                      1!164.3095           h166bdaf_2    conda-forge
x265                      3.5                  h924138e_3    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

**Comment by nicklashansen** [comment] 2024-03-07 00:48
Hi @wertyuilife, thanks for reaching out! We are aware of this issue. It is due to a minor bug in the `SliceSampler` of the `torchrl` package that we depend on for our replay buffer. I recently opened an issue [here](https://github.com/pytorch/rl/issues/1969), and the maintainer of the library has issued a fix [in this PR](https://github.com/pytorch/rl/pull/1982). Updating torchrl to include this fix should resolve your issue. Another option would be to revert the tdmpc2 codebase to an earlier commit before the SliceSampler was introduced, e.g. https://github.com/nicklashansen/tdmpc2/commit/445af9d81d9f459ebeec4f43995ede2ee573e1fd
I hope this helps; sorry for the trouble!

**Comment by wertyuilife** [comment] 2024-03-09 11:22
@nicklashansen sorry for bothering again, but it appears that the [PR](https://github.com/pytorch/rl/pull/1982) you referenced doesn't resolve the bug :O

I updated the `torchrl` package to `torchrl-nightly=2024.3.7` and `tensordict-nightly=2024.3.7`, and reran the command:
```
python train.py task=walker-walk steps=500000 model_size=1 iterations=1 horizon=2
```
However, a new error has occured:
```
...
train            E: 996                   I: 498,500               R: 868.8                 S: 0.0                   T: 10:01:08           
 train            E: 997                   I: 499,000               R: 923.2                 S: 0.0                   T: 10:01:47           
 train            E: 998                   I: 499,500               R: 937.0                 S: 0.0                   T: 10:02:25           
Error executing job with overrides: ['task=walker-walk', 'steps=500000', 'exp_name=test_tdmpc2_new_small_500k', 'seed=1', 'model_size=1', 'iterations=1', 'horizon=2']
Traceback (most recent call last):
  File "/home/wangyuhang/Codes/tdmpc2/tdmpc2/train.py", line 57, in train
    trainer.train()
  File "/home/wangyuhang/Codes/tdmpc2/tdmpc2/trainer/online_trainer.py", line 112, in train
    _train_metrics = self.agent.update(self.buffer)
  File "/home/wangyuhang/Codes/tdmpc2/tdmpc2/tdmpc2.py", line 228, in update
    obs, action, reward, task = buffer.sample()
  File "/home/wangyuhang/Codes/tdmpc2/tdmpc2/common/buffer.py", line 94, in sample
    td = self._buffer.sample().view(-1, self.cfg.horizon+1).permute(1, 0)
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/site-packages/torchrl/data/replay_buffers/replay_buffers.py", line 599, in sample
    ret = self._prefetch_queue.popleft().result()
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/site-packages/torchrl/data/replay_buffers/utils.py", line 50, in decorated_fun
    output = fun(self, *args, **kwargs)
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/site-packages/torchrl/data/replay_buffers/replay_buffers.py", line 533, in _sample
    index, info = self._sampler.sample(self._storage, batch_size)
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/site-packages/torchrl/data/replay_buffers/samplers.py", line 975, in sample
    return self._sample_slices(
  File "/home/wangyuhang/miniconda3/envs/tdmpc2/lib/python3.9/site-packages/torchrl/data/replay_buffers/samplers.py", line 1001, in _sample_slices
    raise RuntimeError(
RuntimeError: Did not find a single trajectory with sufficient length.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
I checked the code and verified that this version (2024.3.7) of the torchrl package includes the aforementioned PR. 
Also, this new error reference to the newly added code in this [file change of the PR](https://github.com/pytorch/rl/pull/1982/files#diff-28eeb1f575ede62ca6ae08d10a93d7db78d777d3a1db8ec524433c64bc67da29), in samplers.py line 979.

It seems that the sampler fails to find any episode with a length exceeding 3(horizon+1)?

**Comment by nicklashansen** [comment] 2024-03-13 23:47
@wertyuilife I will need a bit of time to look into this and see if I can reproduce your error. Thank you for your patience!

**Comment by nicklashansen** [comment] 2024-03-27 19:56
@wertyuilife Hi again, thank you for your patience. This issue has now been addressed in the torchrl library, and I have pinned the latest working version of torchrl/tensordict here https://github.com/nicklashansen/tdmpc2/commit/5f6fadec0fec78304b4b53e8171d348b58cac486. I'll close this issue, but feel free to reopen if you have any follow-up questions!

**Closed by nicklashansen** 2024-03-27 19:56 UTC
